import type { AppState, SectionDef } from "./types";

export const SECTIONS: SectionDef[] = [
  {
    kind: "record",
    id: "basic",
    title: "作品基本情報",
    icon: "01",
    fields: [
      { key: "title", label: "作品タイトル", type: "text", placeholder: "魔王聖典アヴァリティア" },
      { key: "tentativeTitle", label: "仮タイトル", type: "text", placeholder: "悪徳貴族の成り上がり（仮）" },
      { key: "genre", label: "ジャンル", type: "text", placeholder: "ダークファンタジー" },
      { key: "subGenre", label: "サブジャンル", type: "text", placeholder: "成り上がり／復讐劇／頭脳戦" },
      { key: "audience", label: "対象読者", type: "text", placeholder: "20〜40代のWeb小説読者" },
      {
        key: "media",
        label: "想定媒体",
        type: "chips",
        options: ["Web小説", "ライトノベル", "一般文芸", "成人向け", "ゲームシナリオ", "漫画原作"],
      },
      { key: "length", label: "想定文字数", type: "text", placeholder: "30万字" },
      { key: "episodes", label: "想定話数", type: "text", placeholder: "全100話（1話3,000字前後）" },
      {
        key: "concept",
        label: "作品の一言コンセプト",
        type: "textarea",
        placeholder: "処刑寸前の悪徳貴族が邪神と契約し、帝国と聖国を利用して成り上がる物語",
      },
      {
        key: "selling",
        label: "作品の売り",
        type: "textarea",
        placeholder: "主人公の狡猾な頭脳戦と、敵を欺き続ける爽快感。悪役視点ならではの倒錯した正義",
      },
    ],
  },
  {
    kind: "record",
    id: "tone",
    title: "作風・トーン",
    icon: "02",
    fields: [
      { key: "style", label: "文体", type: "text", placeholder: "三人称一元視点。硬質で読みやすい文体" },
      { key: "mood", label: "雰囲気", type: "text", placeholder: "重厚だがテンポは速い。皮肉の効いた会話劇" },
      { key: "aftertaste", label: "読後感", type: "text", placeholder: "ざまぁの爽快感と、次話が気になる引き" },
      {
        key: "emphasis",
        label: "重視する要素",
        type: "chips",
        options: [
          "キャラクター",
          "世界観",
          "ストーリー",
          "会話",
          "バトル",
          "恋愛",
          "心理描写",
          "成り上がり",
          "ざまぁ",
          "ダークさ",
          "官能性",
        ],
      },
      { key: "reference", label: "参考にしたい作風", type: "text", placeholder: "『オーバーロード』のような悪の主人公視点" },
      { key: "avoid", label: "避けたい作風", type: "text", placeholder: "説明過多な地の文。ご都合主義の勝利" },
      { key: "ng", label: "NG表現", type: "textarea", placeholder: "過度なグロ描写、未成年への性的描写、実在の宗教・団体への言及" },
      {
        key: "rules",
        label: "AIに守らせたい文章ルール",
        type: "textarea",
        placeholder: "一文を短く。同じ語尾を3回以上続けない。会話文は改行して読みやすくする",
      },
    ],
  },
  {
    kind: "record",
    id: "world",
    title: "世界観",
    icon: "03",
    fields: [
      { key: "stage", label: "舞台", type: "text", placeholder: "大陸西部のヴァリス帝国と、東の聖アウレア教国" },
      { key: "era", label: "時代", type: "text", placeholder: "中世後期〜近世相当" },
      { key: "civilization", label: "文明レベル", type: "text", placeholder: "火薬は未発達。魔導具が産業と軍事を支える" },
      {
        key: "magic",
        label: "魔法・異能・科学技術",
        type: "textarea",
        placeholder: "血を代償にする魔術体系。教会は『聖印』と呼ばれる奇跡を独占している",
      },
      {
        key: "nations",
        label: "国家・組織",
        type: "textarea",
        placeholder: "帝国貴族院、聖教会、裏社会を牛耳る商業ギルド『黒天秤』",
      },
      { key: "classes", label: "身分制度", type: "text", placeholder: "皇族・貴族・平民・奴隷の四階級" },
      { key: "religion", label: "宗教", type: "text", placeholder: "唯一神アウレア信仰。邪神崇拝は発覚すれば火刑" },
      { key: "economy", label: "経済", type: "text", placeholder: "魔石が基軸通貨。流通は教会が実質的に支配" },
      {
        key: "systems",
        label: "主要システム（迷宮・戦争・学園・ギルドなど）",
        type: "textarea",
        placeholder: "帝都地下に広がる大迷宮。攻略権は貴族の利権となっている",
      },
      {
        key: "commonSense",
        label: "世界の常識",
        type: "textarea",
        placeholder: "邪神は300年前に滅ぼされたとされている。魔術師は教会の認可制",
      },
      {
        key: "contradictions",
        label: "世界の矛盾や問題点",
        type: "textarea",
        placeholder: "聖女伝説の記録が100年分だけ、意図的に消されている",
      },
      {
        key: "start",
        label: "物語開始時点の状況",
        type: "textarea",
        placeholder: "主人公は謀反の濡れ衣で全財産を没収され、処刑を三日後に控えている",
      },
    ],
  },
  {
    kind: "record",
    id: "protagonist",
    title: "主人公",
    icon: "04",
    fields: [
      { key: "name", label: "名前", type: "text", placeholder: "ヴァイス・フォン・グランツベルク" },
      { key: "age", label: "年齢", type: "text", placeholder: "24歳" },
      { key: "gender", label: "性別", type: "text", placeholder: "男性" },
      { key: "appearance", label: "外見", type: "textarea", placeholder: "銀髪に鋭い金眼。没落してなお貴族の気品を崩さない" },
      { key: "position", label: "立場", type: "text", placeholder: "元・帝国伯爵。現在は罪人として投獄中" },
      { key: "personality", label: "性格", type: "textarea", placeholder: "冷徹で計算高いが、身内と認めた者には義理堅い" },
      { key: "desire", label: "欲望", type: "textarea", placeholder: "失った権力を取り戻し、自分を見下した者たちを支配する" },
      { key: "weakness", label: "弱点", type: "textarea", placeholder: "亡き妹に似た境遇の人間を見捨てられない" },
      { key: "secret", label: "秘密", type: "textarea", placeholder: "実は皇帝の隠し子であり、粛清の真の標的だった" },
      { key: "ability", label: "能力", type: "textarea", placeholder: "邪神との契約で得た『契約魔術』。対価を払えば他者の心を縛れる" },
      { key: "initial", label: "初期状態", type: "textarea", placeholder: "地位も財産も失い、処刑を待つだけの死刑囚" },
      { key: "change", label: "最終的な変化", type: "textarea", placeholder: "復讐の果てに、支配ではなく共に立つ者を選べるようになる" },
      { key: "presentation", label: "読者にどう見せたいか", type: "textarea", placeholder: "悪役なのに応援したくなる、頭の切れるダークヒーロー" },
      { key: "charm", label: "主人公の魅力", type: "textarea", placeholder: "常に相手の三手先を読む知略と、決して媚びない矜持" },
      { key: "flaw", label: "主人公の欠点", type: "textarea", placeholder: "他人を駒としか見られず、信頼の築き方を知らない" },
    ],
  },
  {
    kind: "list",
    id: "characters",
    title: "主要キャラクター",
    icon: "05",
    itemLabel: "キャラクター",
    addLabel: "キャラクターを追加",
    titleKey: "name",
    fields: [
      { key: "name", label: "名前", type: "text", placeholder: "リゼット・マーロウ" },
      { key: "role", label: "役割", type: "text", placeholder: "ヒロイン／相棒" },
      { key: "age", label: "年齢", type: "text", placeholder: "19歳" },
      { key: "gender", label: "性別", type: "text", placeholder: "女性" },
      { key: "appearance", label: "外見", type: "text", placeholder: "亜麻色の髪の修道女。左手に聖印の焼き印" },
      { key: "personality", label: "性格", type: "textarea", placeholder: "献身的だが芯が強く、正しさのためなら教会にも逆らう" },
      { key: "goal", label: "目的", type: "textarea", placeholder: "消された聖女伝説の真実を突き止める" },
      { key: "relation", label: "主人公との関係", type: "textarea", placeholder: "処刑場で主人公を救った共犯者。互いに利用し合う関係から始まる" },
      { key: "ability", label: "能力", type: "textarea", placeholder: "触れた者の傷と記憶を読み取る『聖痕』" },
      { key: "secret", label: "秘密", type: "textarea", placeholder: "彼女こそが記録から消された聖女の末裔" },
      { key: "speech", label: "口調", type: "text", placeholder: "丁寧語。感情が昂ると故郷の訛りが出る" },
      { key: "storyRole", label: "物語上の役割", type: "textarea", placeholder: "主人公の非情さを揺さぶる良心。終盤の鍵を握る" },
      { key: "change", label: "最終的な変化", type: "textarea", placeholder: "盲目的な信仰を捨て、自分の意思で祈ることを選ぶ" },
    ],
  },
  {
    kind: "record",
    id: "conflict",
    title: "敵・対立構造",
    icon: "06",
    fields: [
      { key: "boss", label: "最大の敵", type: "textarea", placeholder: "聖教会の枢機卿ザハーク。邪神復活を密かに企む真の黒幕" },
      { key: "midBoss", label: "中ボス", type: "textarea", placeholder: "主人公を陥れた政敵ロデリク侯爵。帝国側の障害" },
      { key: "organization", label: "敵組織", type: "textarea", placeholder: "聖教会の異端審問局。各国に潜む『浄化の刃』" },
      { key: "reason", label: "主人公と敵の対立理由", type: "textarea", placeholder: "主人公の粛清はザハークの計画の一部だった" },
      { key: "ideology", label: "思想の対立", type: "textarea", placeholder: "『力による支配』対『信仰による救済（の名を借りた支配）』" },
      { key: "interest", label: "利害の対立", type: "textarea", placeholder: "邪神の力を奪い合う。主人公の契約こそザハークが求めるもの" },
      { key: "emotion", label: "感情の対立", type: "textarea", placeholder: "ザハークは主人公の父を敬愛しており、その息子を憎悪している" },
      { key: "finalBattle", label: "最終決戦の構図", type: "textarea", placeholder: "邪神復活の儀式の場で、帝国軍と教国軍が激突する中の一騎打ち" },
    ],
  },
  {
    kind: "record",
    id: "story",
    title: "ストーリー構成",
    icon: "07",
    fields: [
      { key: "incident", label: "物語開始時の事件", type: "textarea", placeholder: "処刑前夜、独房に邪神を名乗る声が響き、契約を持ちかけられる" },
      { key: "act1", label: "第一幕", type: "textarea", placeholder: "処刑場からの脱出と、裏社会での再起。最初の復讐相手を罠に嵌める" },
      { key: "act2", label: "第二幕", type: "textarea", placeholder: "貴族社会への復帰と教会との暗闘。仲間が増える一方、契約の代償が牙を剥く" },
      { key: "act3", label: "第三幕", type: "textarea", placeholder: "黒幕の正体判明。復讐と世界の存亡を天秤にかける決断" },
      { key: "climax", label: "クライマックス", type: "textarea", placeholder: "邪神復活の儀式を巡る最終決戦。主人公は契約の全代償を支払う" },
      { key: "ending", label: "エンディング", type: "textarea", placeholder: "帝国の頂点に立つが、玉座の隣には初めて『駒ではない者』がいる" },
      { key: "twist", label: "どんでん返し", type: "textarea", placeholder: "邪神の正体は、初代聖女の成れの果てだった" },
      { key: "growth", label: "主人公の成長曲線", type: "textarea", placeholder: "復讐だけの男 → 守るものを持つ支配者へ。非情さは失わない" },
      { key: "others", label: "ヒロインや仲間の変化", type: "textarea", placeholder: "リゼットは信仰と決別し、仲間たちは打算から本物の忠誠へ変わる" },
      { key: "theme", label: "物語全体のテーマ", type: "textarea", placeholder: "「正義は誰が定義するのか」「悪は救いになり得るか」" },
    ],
  },
  {
    kind: "list",
    id: "chapters",
    title: "章構成",
    icon: "08",
    itemLabel: "章",
    addLabel: "章を追加",
    titleKey: "title",
    fields: [
      { key: "title", label: "章タイトル", type: "text", placeholder: "第一章「処刑台の契約」" },
      { key: "purpose", label: "章の目的", type: "textarea", placeholder: "主人公の転落と契約を描き、物語のルールを提示する" },
      { key: "start", label: "章の開始状況", type: "textarea", placeholder: "処刑三日前。独房で全てを失った主人公" },
      { key: "events", label: "章の主な事件", type: "textarea", placeholder: "邪神との契約、処刑場での脱出劇、リゼットとの出会い" },
      { key: "highlight", label: "章の見せ場", type: "textarea", placeholder: "処刑台の上で群衆に向かい、堂々と『復讐宣言』をする場面" },
      { key: "end", label: "章の終了状況", type: "textarea", placeholder: "裏社会の酒場で潜伏を開始。最初の標的が決まる" },
      { key: "hook", label: "次章への引き", type: "textarea", placeholder: "「まずは、私を売った男の顔を見に行こうか」" },
    ],
  },
  {
    kind: "list",
    id: "scenes",
    title: "シーン構成",
    icon: "09",
    itemLabel: "シーン",
    addLabel: "シーンを追加",
    titleKey: "title",
    fields: [
      { key: "number", label: "シーン番号", type: "text", placeholder: "1-1" },
      { key: "title", label: "シーンタイトル", type: "text", placeholder: "独房の声" },
      { key: "characters", label: "登場人物", type: "text", placeholder: "ヴァイス、邪神（声のみ）" },
      { key: "place", label: "場所", type: "text", placeholder: "帝都地下牢・独房" },
      { key: "purpose", label: "目的", type: "textarea", placeholder: "主人公の絶望と、契約に至る心理の必然性を描く" },
      { key: "events", label: "起きる出来事", type: "textarea", placeholder: "壁の血文字が輝き、邪神が契約を持ちかける。主人公は条件を交渉する" },
      { key: "emotion", label: "感情の変化", type: "textarea", placeholder: "絶望 → 警戒 → 野心の再燃" },
      { key: "impression", label: "読者に与えたい印象", type: "textarea", placeholder: "「悪魔相手にすら交渉するのか」という主人公の底知れなさ" },
      { key: "hook", label: "次シーンへの引き", type: "textarea", placeholder: "契約成立の瞬間、看守の悲鳴が響く" },
    ],
  },
  {
    kind: "list",
    id: "foreshadows",
    title: "伏線管理",
    icon: "10",
    itemLabel: "伏線",
    addLabel: "伏線を追加",
    titleKey: "name",
    fields: [
      { key: "name", label: "伏線名", type: "text", placeholder: "古い聖女伝説" },
      { key: "intro", label: "初出", type: "text", placeholder: "第一章。酒場の老人が語る昔話として" },
      { key: "presentation", label: "読者への見せ方", type: "textarea", placeholder: "世界観の雰囲気づくりの小話に見せかけ、重要性を悟らせない" },
      { key: "truth", label: "真相", type: "textarea", placeholder: "伝説の聖女は邪神そのものであり、主人公の能力の由来と繋がる" },
      { key: "payoff", label: "回収予定", type: "text", placeholder: "最終章。邪神の正体が明かされる場面" },
      { key: "effect", label: "回収時の効果", type: "textarea", placeholder: "序盤から読み返したくなる衝撃と、敵味方の構図の反転" },
    ],
  },
  {
    kind: "record",
    id: "instructions",
    title: "AIへの作業指示",
    icon: "11",
    fields: [
      {
        key: "tasks",
        label: "AIにやらせたい作業",
        type: "chips",
        options: [
          "企画作成",
          "プロット作成",
          "章構成作成",
          "シーン作成",
          "本文執筆",
          "リライト",
          "矛盾チェック",
          "キャラ口調チェック",
          "伏線チェック",
        ],
      },
      { key: "format", label: "出力形式", type: "text", placeholder: "Markdown形式。話数ごとに見出しを付ける" },
      { key: "count", label: "文字数", type: "text", placeholder: "1話あたり3,000〜4,000字" },
      { key: "style", label: "文体指定", type: "text", placeholder: "上記「作風・トーン」の文体を厳守" },
      {
        key: "checks",
        label: "チェックしてほしい点",
        type: "textarea",
        placeholder: "設定との矛盾、キャラの口調ブレ、伏線の張り忘れ・回収漏れ",
      },
      {
        key: "mustRules",
        label: "絶対に守るルール",
        type: "textarea",
        placeholder: "設定資料にない固有名詞を勝手に作らない。不明点は執筆前に質問する",
      },
      {
        key: "forbidden",
        label: "やってはいけないこと",
        type: "textarea",
        placeholder: "キャラを設定と矛盾する行動をさせる。世界観のルールを破る展開",
      },
    ],
  },
];

/** 出力プロンプト末尾に常に付与する厳守事項 */
export const STRICT_RULES = [
  "設定と本文を混同しないこと",
  "キャラクターの目的と口調を維持すること",
  "世界観のルールを破らないこと",
  "伏線を忘れないこと",
  "説明過多にせず、場面・行動・会話で描写すること",
  "不明点がある場合は勝手に確定せず、候補を提示すること",
];

export function createEmptyState(): AppState {
  const records: AppState["records"] = {};
  const lists: AppState["lists"] = {};
  for (const section of SECTIONS) {
    if (section.kind === "record") {
      const values: Record<string, string | string[]> = {};
      for (const field of section.fields) {
        values[field.key] = field.type === "chips" ? [] : "";
      }
      records[section.id] = values;
    } else {
      lists[section.id] = [];
    }
  }
  return { records, lists, hiddenSections: [] };
}
